# Generated by Django 4.2.7 on 2023-11-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
    ]
