# Generated by Django 4.2.6 on 2023-11-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='text1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
